---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - stable.aws.parameters.com
  resources:
  - ssmparameters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stable.aws.parameters.com
  resources:
  - ssmparameters/finalizers
  verbs:
  - update
- apiGroups:
  - stable.aws.parameters.com
  resources:
  - ssmparameters/status
  verbs:
  - get
  - patch
  - update
