# This rule is not used by the project aws-parameters itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the stable.aws.parameters.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: aws-parameters
    app.kubernetes.io/managed-by: kustomize
  name: ssmparameter-editor-role
rules:
- apiGroups:
  - stable.aws.parameters.com
  resources:
  - ssmparameters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stable.aws.parameters.com
  resources:
  - ssmparameters/status
  verbs:
  - get
