# This rule is not used by the project aws-parameters itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over stable.aws.parameters.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: aws-parameters
    app.kubernetes.io/managed-by: kustomize
  name: ssmparameter-admin-role
rules:
- apiGroups:
  - stable.aws.parameters.com
  resources:
  - ssmparameters
  verbs:
  - '*'
- apiGroups:
  - stable.aws.parameters.com
  resources:
  - ssmparameters/status
  verbs:
  - get
