kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30950 # ExposedApp
        hostPort: 3000
      - containerPort: 30900 # prometheus
        hostPort: 9090