apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mydeployments.stable.demo.com
spec:
  group: stable.demo.com
  scope: Namespaced
  names:
    kind: MyDeployment
    plural: mydeployments
    singular: mydeployment
    shortNames:
      - md
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - jsonPath: .status.deploymentName
          name: DeploymentName
          type: string
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                image:
                  type: string
            status:
              type: object
              properties:
                deploymentName:
                  type: string
