FROM golang:alpine as builder

COPY . /workspace
WORKDIR /workspace

RUN go build -o bin/main
RUN adduser -u 1001 -s /bin/bash -D minimal-controller

FROM scratch
COPY --from=builder /workspace/bin/main /bin/main
COPY --from=builder /etc/passwd /etc/passwd
USER 1001
CMD ["/bin/main"]