apiVersion: stable.k3builder.com/v1
kind: ExposedApp
metadata:
  name: demo-exposed-app
  namespace: example
spec:
  replicas: 2
  image: "nginx:latest"
  protocol: TCP
  port: 3000
  containerPort: 80
  nodePort: 30950
  serviceType: "NodePort"