apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: webhook-conditions
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: webhook-conditions
    spec:
      volumes:
        - name: certificate
          secret:
            secretName: SECRET_NAME
      containers:
        - name: main
          image: "${IMG}"
          env:
            - name: CERT_FILE
              value: /etc/ssl/private/tls.crt
            - name: KEY_FILE
              value: /etc/ssl/private/tls.key
          volumeMounts:
            - mountPath: /etc/ssl/private
              name: certificate
              readOnly: true
          livenessProbe:
            httpGet:
              port: 8080
              path: /healthz
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 5
          ports:
            - containerPort: 8080
