FROM python:3.12-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
RUN useradd -u 1001 -ms /bin/bash webhook
USER 1001
COPY --chown=1001 . /home/webhook
WORKDIR /home/webhook
RUN uv sync --frozen --no-cache

CMD ["/home/webhook/.venv/bin/fastapi", "run", "main.py", "--port", "8080", "--host", "0.0.0.0"]