# This rule is not used by the project k3builder itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the stable.k3builder.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k3builder
    app.kubernetes.io/managed-by: kustomize
  name: exposedapp-editor-role
rules:
- apiGroups:
  - stable.k3builder.com
  resources:
  - exposedapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stable.k3builder.com
  resources:
  - exposedapps/status
  verbs:
  - get
