# This rule is not used by the project k3builder itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over stable.k3builder.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k3builder
    app.kubernetes.io/managed-by: kustomize
  name: exposedapp-admin-role
rules:
- apiGroups:
  - stable.k3builder.com
  resources:
  - exposedapps
  verbs:
  - '*'
- apiGroups:
  - stable.k3builder.com
  resources:
  - exposedapps/status
  verbs:
  - get
