---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - stable.k3builder.com
  resources:
  - exposedapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stable.k3builder.com
  resources:
  - exposedapps/finalizers
  verbs:
  - update
- apiGroups:
  - stable.k3builder.com
  resources:
  - exposedapps/status
  verbs:
  - get
  - patch
  - update
