apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: system
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: no-library
  template:
    metadata:
      labels:
        app.kubernetes.io/name: no-library
    spec:
      serviceAccountName: SA_NAME
      containers:
        - name: manager
          image: "${IMAGE}"
          env:
            - name: PORT
              value: "8080"
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
          livenessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 20
            httpGet:
              port: 8080
              path: /healthz