resources:
  - service_account.yaml
  - cluster_role.yaml
  - cluster_role_binding.yaml
replacements:
  - source:
      kind: ServiceAccount
      fieldPath: metadata.name
    targets:
      - select:
          kind: ClusterRoleBinding
        fieldPaths:
          - subjects.0.name
  - source:
      kind: ServiceAccount
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: ClusterRoleBinding
        fieldPaths:
          - subjects.0.namespace
  - source:
      kind: ClusterRole
      fieldPath: metadata.name
    targets:
      - select:
          kind: ClusterRoleBinding
        fieldPaths:
          - roleRef.name