apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-role
rules:
  - verbs:
      - "update"
      - "get"
      - "list"
      - "watch"
    apiGroups:
      - "apps"
    resources:
      - "deployments"