apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster_role_binding
subjects:
  - kind: ServiceAccount
    name: SA_NAME
    namespace: SA_NAMESPACE
roleRef:
  kind: ClusterRole
  name: CLUSTER_ROLE_NAME
  apiGroup: rbac.authorization.k8s.io