apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webhook-conditions
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webhook-conditions
    spec:
      serviceAccountName: SA_NAME
      securityContext:
        runAsNonRoot: true
      containers:
        - name: main
          image: "${IMG}"
