apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate
  namespace: system
spec:
  secretName: app-certificate
  issuerRef:
    name: actix-webhooks-ca-issuer
    kind: Issuer
  dnsNames:
    - actix-webhooks-service.actix-webhooks-system.svc