apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook
  annotations:
    cert-manager.io/inject-ca-from: actix-webhooks-system/actix-webhooks-certificate
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: actix-webhooks-service
        namespace: actix-webhooks-system
        path: /modify
        port: 8080
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations:
          - "CREATE"
          - "UPDATE"
        resources: ["pods"]
        scope: "Namespaced"
    name: mutate.actix-webhooks.com
    timeoutSeconds: 10
    sideEffects: None