[package]
name = "actix-webhooks"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = { version = "4.10.2", features = ["openssl"] }
openssl = "0.10.72"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
