namespace: webhook-system
namePrefix: webhook-
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - secret.yaml
  - issuer.yaml
  - validating_webhook.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: ingress-nginx-controller-internal.ingress-nginx.svc
    target:
      kind: Ingress
      name: ingress
      namespace: system
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: ingress-nginx-controller-internal.ingress-nginx.svc
    target:
      kind: Ingress
      name: ingress
      namespace: system

replacements:
  - source:
      kind: Service
      fieldPath: metadata.name
    targets:
      - select:
          kind: Ingress
        fieldPaths:
          - spec.rules.0.http.paths.0.backend.service.name
  - source:
      kind: Secret
      fieldPath: metadata.name
    targets:
      - select:
          kind: Ingress
        fieldPaths:
          - spec.tls.0.secretName
      - select:
          kind: ValidatingWebhookConfiguration
        fieldPaths:
          - metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          delimiter: "/"
          index: 1
  - source:
      kind: Secret
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: ValidatingWebhookConfiguration
        fieldPaths:
          - metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          delimiter: "/"
          index: 0
  - source:
      kind: Issuer
      fieldPath: metadata.name
    targets:
      - select:
          kind: Ingress
        fieldPaths:
          - metadata.annotations.[cert-manager.io/issuer]