apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: no-library-role
rules:
  - verbs:
      - "get"
      - "watch"
      - "list"
    apiGroups:
      - "stable.no-library.com"
    resources:
      - "exposedapps"