apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: exposedapps.stable.no-library.com
spec:
  group: stable.no-library.com
  scope: Namespaced
  names:
    kind: ExposedApp
    plural: exposedapps
    singular: exposedapp
    shortNames:
      - ea
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - jsonPath: .status.deploymentName
          name: DeploymentName
          type: string
        - jsonPath: .status.serviceName
          name: ServiceName
          type: string
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                image:
                  type: string
                  x-kubernetes-validations:
                    - rule: "self.split(':')[1] != 'latest'"
                      message: "'latest' tag not allowed"
                protocol:
                  type: string
                  enum: ["TCP", "UDP", "SCTP"]
                port:
                  type: integer
                  minimum: 0
                  maximum: 65535
                containerPort:
                  type: integer
                  minimum: 0
                  maximum: 65535
                nodePort:
                  type: integer
                  minimum: 0
                  maximum: 65535
                serviceType:
                  type: string
                  enum: ["ClusterIP", "NodePort", "LoadBalancer", "ExternalName"]
            status:
              type: object
              properties:
                deploymentName:
                  type: string
                serviceName:
                  type: string
