apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: exposedapps.stable.no-library.com
spec:
  group: stable.no-library.com
  scope: Namespaced
  names:
    kind: ExposedApp
    plural: exposedapps
    singular: exposedapp
    shortNames:
      - ea
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                image:
                  type: string
                protocol:
                  type: string
                port:
                  type: integer
                containerPort:
                  type: integer
                nodePort:
                  type: integer
                serviceType:
                  type: string