apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-library
  namespace: no-library
  labels:
    app.kubernetes.io/name: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: no-library
  template:
    metadata:
      name: no-library
      labels:
        app.kubernetes.io/instance: no-library
    spec:
      serviceAccountName: no-library
      securityContext:
        runAsNonRoot: true
      containers:
        - name: manager
          image: "${IMAGE}"
          env:
            - name: PORT
              value: "8080"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 20
            httpGet:
              port: 8080
              path: /healthz
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              port: 8080
              path: /healthz