resources:
  - namespace.yaml
  - deployment.yaml
  - service_account.yaml
labels:
  - pairs:
      app.kubernetes.io/instance: no-library
      app.kubernetes.io/component: manager
      app.kubernetes.io/created-by: no-library
      app.kubernetes.io/part-of: no-library
      app.kubernetes.io/managed-by: kustomize
    includeTemplates: true