apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: no-library
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: no-library
    app.kubernetes.io/part-of: no-library
    app.kubernetes.io/managed-by: kustomize
  name: no-library