apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: no-library-role-binding
  namespace: no-library
subjects:
  - kind: ServiceAccount
    name: no-library
    namespace: no-library
roleRef:
  kind: Role
  name: no-library-role
  apiGroup: rbac.authorization.k8s.io