apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: no-library-role
  namespace: no-library
rules:
  - verbs:
      - "get"
      - "update"
      - "patch"
    apiGroups:
      - "coordination.k8s.io"
    resources:
      - "leases"