kustomize-bin := justfile_directory() + "/bin/kustomize"

kustomize:
    make kustomize

deploy:
    #!/bin/bash -e
    TAG=$(date +%s)
    export IMG="controller:${TAG}"
    make manifests docker-build
    kind load docker-image "${IMG}"
    make deploy

example-apply:
    kustomize build example | kubectl apply -f -