FROM rust:slim as builder
COPY . /workspace
WORKDIR /workspace
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && apt-get install -y pkg-config libssl-dev
RUN --mount=type=cache,target=/workspace/target,sharing=locked cargo build --release

FROM debian:12-slim
RUN apt-get update && apt-get install -y openssl ca-certificates libssl-dev
RUN useradd -u 1001 -ms /bin/bash no-library
COPY --from=builder /workspace/target/release/no-library /bin/no-library
USER 1001
CMD ["/bin/no-library"]